### ISSUE TITLE
Evaluation script

### ISSUE THREAD

**Issue by LuigiSigillo** [vishalned/MMEarth-train#8]
Hi, thank you for the great work.
Could you provide an evaluation script to reach the same metrics you reported on the paper, using the checkpoints model you kindly shared? Moreover, in another issue you say that it is possible not to use the Minkowski convolution if you only want to test the model, but when loading the model I find strange mismatch error, even following your tutorial notebook.
THank you

**Comment by vishalned** [comment]
Hey, 

The evaluation scripts are the ones using slurm. You can find a sample one [here](https://github.com/vishalned/MMEarth-train/blob/main/slurm_scripts/slurm_fine_tune_all.sh). 

Minkowski engine and convolutions are only needed for pre-training since we make use of the sparse convolutions. When finetuning, these are replaced by normal convolutions and hence it is not required. Thanks for pointing out the issue with the tutorial, i need to change this. Perhaps the solution in this issue might help you - https://github.com/vishalned/MMEarth-train/issues/6#issuecomment-2330330866. I have also done something similar when finetuning the models
